<?php

namespace Kendoctor\Bundle\NodeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCategoryRepository extends EntityRepository
{
    public function getCategoryWithPages($id)
    {
        $query =  $this->_em->createQuery("
            SELECT c, p
            FROM KendoctorNodeBundle:PageCategory c
            LEFT JOIN c.pages p
            WHERE c.id = :id
            ")
                ->setParameter("id", $id);
        
        return $query->getOneOrNullResult();        
    }
}
