jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Kendoctor\Bundle\NodeBundle\Entity\User:
          algorithm: sha1
          iterations: 1
          encode_as_base64: true
          
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
          chain:
            providers: [main, in_memory]
            
        main:
          entity:
            class: Kendoctor\Bundle\NodeBundle\Entity\User
            property: username
            
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        login:
            pattern:  ^/login$
            anonymous: ~
        
        register:
            pattern: ^/register$            
            security: false      
            
        main:
            pattern: ^/
            form_login:
              check_path: /login_check
              login_path: login
            logout:
              path: logout
              target: /
            #anonymous: ~
            provider: chain_provider
              
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

       

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:

